### ISSUE TITLE
Can't generate large-v3 Core ML model

### ISSUE THREAD

**Issue by davidpoblador** [ggerganov/whisper.cpp#1454]
After the release of whisper large-v3 I can't generate the Core ML model (still works fine for the [now previous] large-v2 one):

```
(.venv) dpoblador@lemon ~/repos/whisper.cpp ±master⚡ » ./models/generate-coreml-model.sh large

ModelDimensions(n_mels=128, n_audio_ctx=1500, n_audio_state=1280, n_audio_head=20, n_audio_layer=32, n_vocab=51866, n_text_ctx=448, n_text_state=1280, n_text_head=20, n_text_layer=32)
Traceback (most recent call last):
  File "/Users/dpoblador/repos/whisper.cpp/models/convert-whisper-to-coreml.py", line 323, in <module>
    encoder = convert_encoder(hparams, encoder, quantize=args.quantize)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dpoblador/repos/whisper.cpp/models/convert-whisper-to-coreml.py", line 257, in convert_encoder
    traced_model = torch.jit.trace(model, input_data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dpoblador/repos/whisper.cpp/.venv/lib/python3.11/site-packages/torch/jit/_trace.py", line 798, in trace
    return trace_module(
           ^^^^^^^^^^^^^
  File "/Users/dpoblador/repos/whisper.cpp/.venv/lib/python3.11/site-packages/torch/jit/_trace.py", line 1065, in trace_module
    module._c._create_method_from_trace(
  File "/Users/dpoblador/repos/whisper.cpp/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dpoblador/repos/whisper.cpp/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dpoblador/repos/whisper.cpp/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dpoblador/repos/whisper.cpp/.venv/lib/python3.11/site-packages/whisper/model.py", line 162, in forward
    x = F.gelu(self.conv1(x))
               ^^^^^^^^^^^^^
  File "/Users/dpoblador/repos/whisper.cpp/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dpoblador/repos/whisper.cpp/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dpoblador/repos/whisper.cpp/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dpoblador/repos/whisper.cpp/.venv/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dpoblador/repos/whisper.cpp/.venv/lib/python3.11/site-packages/whisper/model.py", line 48, in _conv_forward
    return super()._conv_forward(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dpoblador/repos/whisper.cpp/.venv/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 306, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Given groups=1, weight of size [1280, 128, 3], expected input[1, 80, 3000] to have 128 channels, but got 80 channels instead
coremlc: error: Model does not exist at models/coreml-encoder-large.mlpackage -- file:///Users/dpoblador/repos/whisper.cpp/
mv: rename models/coreml-encoder-large.mlmodelc to models/ggml-large-encoder.mlmodelc: No such file or directory
```

**Comment by davidpoblador** [comment]
Related to this https://github.com/ggerganov/whisper.cpp/issues/1437#issuecomment-1801886311
