### ISSUE TITLE
convert-whisper-to-openvino.py doesn't work for large-v3-turbo

### ISSUE THREAD

**Issue by BBBalls** [ggerganov/whisper.cpp#2441]
```
(openvino_conv_env) usr@pop-os:/whisper.cpp/models$ python convert-whisper-to-openvino.py --model large-v3-turbo
Traceback (most recent call last):
  File "//whisper.cpp/models/convert-whisper-to-openvino.py", line 54, in <module>
    whisper = load_model(args.model).cpu()
  File "/whisper.cpp/models/openvino_conv_env/lib/python3.10/site-packages/whisper/__init__.py", line 139, in load_model
    raise RuntimeError(
RuntimeError: Model large-v3-turbo not found; available models = ['tiny.en', 'tiny', 'base.en', 'base', 'small.en', 'small', 'medium.en', 'medium', 'large-v1', 'large-v2', 'large-v3', 'large']
```

Pop!_OS 22.04
Python 3.10.12

**Comment by baristikir** [comment]
It looks like your local version of [openai/whisper](https://github.com/openai/whisper) is not matching the latest version since the [list](https://github.com/openai/whisper/blob/25639fc17ddc013d56c594bfbf7644f2185fad84/whisper/__init__.py#L30) now contains 'large-v3-turbo'. Updating your local whisper dependency should fix it.

**Comment by BBBalls** [comment]
Thank you.
