### ISSUE TITLE
Vulkan crashes

### ISSUE THREAD

**Issue by jech** [ggerganov/whisper.cpp#2559]
The vulkan build has started crashing on my machine.  Reverting to 300c07b94deb2de0b679dd8eab58c67e54b4e4cb fixes the issue.  A backtrace follows.

```
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:76
#1  0x00007ffff7987b60 in __printf_buffer (buf=buf@entry=0x7fffffffb570, 
    format=0x5555556e7dd8 "ggml_vulkan: %d = %s (%s) | uma: %d | fp16: %d | w size: %d\n", ap=0x7fffffffb718, mode_flags=mode_flags@entry=0)
    at ./stdio-common/vfprintf-process-arg.c:435
#2  0x00007ffff79aaeae in __vsnprintf_internal (
    string=0x7fffffffb650 "ggml_vulkan: 0 = Intel(R) UHD Graphics 620 (KBL GT(", maxlen=128, format=0x7fffffffb570 "P\266\377\377\377\177", 
    args=0x5555556e7dd8, mode_flags=0) at ./libio/vsnprintf.c:96
#3  ___vsnprintf (
    string=string@entry=0x7fffffffb650 "ggml_vulkan: 0 = Intel(R) UHD Graphic20 (KBL GT2) (", maxlen=maxlen@entry=128, 
    format=format@entry=0x5555556e7dd8 "ggml_vulkan: %d = %s (%s) | uma: %d |16: %d | warp size: %d\n", args=args@entry=0x7fffffffb718)
    at ./libio/vsnprintf.c:103
#4  0x00005555555e8a0f in ggml_log_internal_v (level=GGML_LOG_LEVEL_DEBUG, 
    format=0x5555556e7dd8 "ggml_vulkan: %d = %s (%s) | uma: %d | fp16: %d | w size: %d\n", args=args@entry=0x7fffffffb718) at ggml/src/ggml.c:334
#5  0x00005555555edd3f in ggml_log_internal (level=<optimized out>, 
    format=<optimized out>) at ggml/src/ggml.c:350
#6  0x00005555555af53c in ggml_vk_print_gpu_info (idx=idx@entry=0)
    at /usr/include/c++/14/bits/basic_string.h:227
#7  0x00005555555b10e8 in ggml_vk_instance_init ()
--Type <RET> for more, q to quit, c to continue without paging--c
    at ggml/src/ggml-vulkan.cpp:2229
#8  0x00005555555b1ca9 in ggml_vk_get_device_count ()
    at ggml/src/ggml-vulkan.cpp:6167
#9  ggml_backend_vk_get_device_count () at ggml/src/ggml-vulkan.cpp:6631
#10 0x00005555555b1cc9 in ggml_backend_vk_reg_get_device_count (
    reg=<optimized out>) at ggml/src/ggml-vulkan.cpp:6878
#11 0x0000555555636009 in ggml_backend_registry::register_backend (
    this=0x5555559847c0 <get_reg()::reg>, reg=<optimized out>)
    at ggml/src/ggml-backend.cpp:609
#12 ggml_backend_registry::ggml_backend_registry (
    this=0x5555559847c0 <get_reg()::reg>) at ggml/src/ggml-backend.cpp:583
#13 get_reg () at ggml/src/ggml-backend.cpp:623
#14 0x0000555555636139 in ggml_backend_reg_count ()
    at ggml/src/ggml-backend.cpp:638
#15 0x000055555568be0e in whisper_init_with_params_no_state (
    loader=loader@entry=0x7fffffffdb40, params=...) at src/whisper.cpp:3671
#16 0x000055555568c378 in whisper_init_from_file_with_params_no_state (
    path_model=0x55555599bec0 "models/ggml-base.en.bin", params=...)
    at src/whisper.cpp:3611
#17 0x000055555568fabd in whisper_init_from_file_with_params (
    path_model=<optimized out>, 
    params=<error reading variable: Cannot access memory at address 0x0>)
    at src/whisper.cpp:3689
#18 0x00005555556e154c in whisper_bench_full (params=...)
    at /usr/include/c++/14/bits/basic_string.h:227
#19 0x000055555558f409 in main (argc=1, argv=0x7fffffffe8c8)
    at examples/bench/bench.cpp:168
```

**Comment by jech** [comment]
Apparently no longer the case.
