### ISSUE TITLE
Generated vtt/srt/txt contains invalid UTF-8 character

### ISSUE THREAD

**Issue by dodysw2** [ggerganov/whisper.cpp#438]
Noticed rarely whisper cpp generates .txt, .vtt, and .vrt that contains invalid UTF-8 byte character. Would this be something expected from the whisper model that the user needs to handle? 
```
>>> open('454912_614694.wav.vtt','rb').read().decode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 31479: invalid start byte
>>> open('454912_614694.wav.vtt','rb').read()[31400:31500]
b'garam\n\n00:39:42.720 --> 00:39:44.880\n 10g garam\n\n00:39:44.880 --> 00:39:56.120\n\x98\n\n00:39:56.120 --> 0' 
```

**Comment by ggerganov** [comment]
This is unexpected. If possible - provide repro steps. Closing for now

**Comment by bebound** [comment]
Similar error when reading json output with `output = json.load(f)`:
Running whisper again can fix the issue.

PS: The output log looks good, don't know why json is incorrect.
```
  File   File "/Users/kk/Developer/PycharmProjects/audio-script/main.py", line 171, in whisper
    output = json.load(f)
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 29724-29725: invalid continuation byte
```

**Comment by uncle-rennus** [comment]
Here I had the same problem, but the issue was in Windows Terminal: 
I had to force the command prompt to use chcp 65001 for utf-8 rendering. Just change the settings.json on Windows Terminal config:

`"commandline": "cmd.exe /k chcp 65001 & C:/msys64/msys2_shell.cmd -defterm -here -no-start -ucrt64 -shell bash"`
