### ISSUE TITLE
I cant access main function via dart:ffi.

### ISSUE THREAD

**Issue by turgayh** [ggerganov/whisper.cpp#750]
Hello everyone , 
I'm trying to read libwhisper.so with dart:ffi but I can't access the main function. 

I have tried many ways to access the whisper.cpp module in dart but without success. 

Are there any plans to create a package for dart language? 

Basicall i wanna access main function into whisper.cpp and use it for dart project . For example flutter project. 

I want to access  `int main(int argc, char ** argv)`  C-API with the following code piece.

```
import 'dart:ffi';

import 'package:ffi/ffi.dart';

void main() {
  final dylib = DynamicLibrary.open('lib/libwhisper.so');

  final int Function(int x, Pointer<Pointer<Utf8>> y) main = dylib
      .lookup<NativeFunction<Int32 Function(Int32, Pointer<Pointer<Utf8>>)>>(
          'main')
      .asFunction();

  final command = ['-f', 'sample.wav'];

  final List<Pointer<Utf8>> myPointers =
      command.map((e) => e.toNativeUtf8()).toList();

  WhisperAllocator allocator = WhisperAllocator();
  final Pointer<Pointer<Utf8>> pointerPointer = allocator
      .allocate<Pointer<Utf8>>(sizeOf<Pointer<Utf8>>() * command.length);
  for (int i = 0; i < command.length; i++) {
    pointerPointer[i] = myPointers[i];
  }

  final result = main(4, pointerPointer);
  print(result);
}

class WhisperAllocator implements Allocator {
  final Allocator _wrappedAllocator;
  int _totalAllocations = 0;
  int _nonFreedAllocations = 0;

  WhisperAllocator([Allocator? allocator])
      : _wrappedAllocator = allocator ?? calloc;

  int get totalAllocations => _totalAllocations;

  int get nonFreedAllocations => _nonFreedAllocations;

  @override
  Pointer<T> allocate<T extends NativeType>(int byteCount, {int? alignment}) {
    final result =
        _wrappedAllocator.allocate<T>(byteCount, alignment: alignment);
    _totalAllocations++;
    _nonFreedAllocations++;
    return result;
  }

  @override
  void free(Pointer<NativeType> pointer) {
    _wrappedAllocator.free(pointer);
    _nonFreedAllocations--;
  }
}

````

**Error Message**

```
Unhandled exception:
Invalid argument(s): Failed to lookup symbol 'main': dlsym(0x7ff905d34c10, main): symbol not found
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
#1      main
main.dart:9
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)

Exited (255)
````

**Comment by ggerganov** [comment]
Use the C-style API

**Comment by Prateek0001** [comment]
Hey someone tried for ios as well load libwhisper.a file using dart ffi
